# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e240c8bb59f1e41704a33a160237f26770745c05a1c076a4ba58ab461683d2cb835bed3cc3d3a1bf1084d212a801a0e9640fb3807cd8e6ed991ef08d1a2ca751

test:
  secret_key_base: cde5dcb991f001709dc5f94597550a922e54d820800b3026e083cc27caa2a7cb51372aa845dea99ff9487af2f07ad4943576b55dbbfdfa433274e880c9149998

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
